"""Changed category field of product

Revision ID: 17d159c32fa4
Revises: 9f0d49f860f9
Create Date: 2024-08-21 13:21:40.633473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d159c32fa4'
down_revision = '9f0d49f860f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.drop_constraint('product_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_category_id_fkey', 'category', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###
