"""added featured column to product

Revision ID: 8d9a8debaad3
Revises: c8c44b44d8a3
Create Date: 2024-08-21 14:58:48.743442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9a8debaad3'
down_revision = 'c8c44b44d8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('featured')

    # ### end Alembic commands ###
