"""Add quantity to Product

Revision ID: 8eb433d0c621
Revises: 598e1d3e1a2e
Create Date: 2024-08-18 15:17:56.117079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb433d0c621'
down_revision = '598e1d3e1a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
