"""added currency column to Product page

Revision ID: a229ba1f1fe8
Revises: 8d9a8debaad3
Create Date: 2024-08-21 16:32:43.033731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a229ba1f1fe8'
down_revision = '8d9a8debaad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
